version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: your-node-app-image
    container_name: node_app
    environment:
      - NODE_ENV=production
      - PROD_DB_USERNAME=root
      - PROD_DB_PASSWORD=admin
      - PROD_DB_NAME=dev_db
      - PROD_DB_HOST=db
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data:
