version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prod_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  flipkart:
    image: flipkart  # Use the local flipkart image
    container_name: flipkart
    ports:
      - "3000:3000"
    environment:
      PORT: 3000  # Replace with your desired port
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
