version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"  # Expose MySQL port for external access if needed
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - my-network

  flipkart:
    image: flipkart
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile for the flipkart service
    container_name: flipkart
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production  # Set NODE_ENV to 'production'
      PROD_DB_USERNAME: admin
      PROD_DB_PASSWORD: admin
      PROD_DB_NAME: dev_db
      PROD_DB_HOST: mysql  # Use the service name 'mysql' as the hostname
    depends_on:
      - mysql  # Ensure mysql starts before flipkart
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
