version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  flipkart:
    image: flipkart  # Use the local flipkart image
    container_name: flipkart
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PROD_DB_USERNAME: admin
      PROD_DB_PASSWORD: admin
      PROD_DB_NAME: dev_db
      PROD_DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
